# Generated by Django 3.2.9 on 2022-01-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('videoid', models.CharField(db_column='videoId', max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('info_one', models.CharField(blank=True, max_length=255, null=True)),
                ('info_two', models.CharField(blank=True, max_length=255, null=True)),
                ('publishedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'youtube_videos',
                'managed': False,
            },
        ),
    ]
